from __future__ import annotations

from typing import Any, ContextManager, Dict, Iterable, List, TypeVar

T = TypeVar("T")

class LM:
    model: str
    history: List[Dict[str, Any]]

    def __init__(
        self,
        model: str,
        *,
        model_type: str | None = ...,
        temperature: float | None = ...,
        max_tokens: int | None = ...,
        cache: bool | None = ...,
        vertex_project: str | None = ...,
        vertex_location: str | None = ...,
        reasoning_effort: str | None = ...,
        api_key: str | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def __call__(self, prompt: str, **kwargs: Any) -> Any: ...
    def copy(self, **kwargs: Any) -> "LM": ...

def configure(*, lm: LM, track_usage: bool | None = ..., **kwargs: Any) -> None: ...

class Example:
    def __init__(self, **kwargs: Any) -> None: ...
    def with_inputs(self, *names: str) -> "Example": ...
    def __getattr__(self, name: str) -> Any: ...

class Evaluate:
    def __init__(self, metric: Any, devset: Any, **kwargs: Any) -> None: ...
    def __call__(self, program: Any) -> Any: ...

class Predict:
    lm: LM | None
    config: dict[str, Any]
    signature: Signature
    def __init__(
        self, signature: Any, *, lm: LM | None = ..., **kwargs: Any
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Prediction: ...
    def get_lm(self) -> LM: ...

class Field(str): ...

def InputField(*, desc: str | None = ..., **kwargs: Any) -> Field: ...
def OutputField(*, desc: str | None = ..., **kwargs: Any) -> T: ...

class Prediction(dict[str, Any]):
    def __init__(self, **kwargs: Any) -> None: ...
    def get_lm_usage(self) -> dict[str, dict[str, int]]: ...
    def __getattr__(self, name: str) -> Any: ...

class Signature:
    instructions: str | None

class Module:
    def __init__(self, callbacks: Iterable[Any] | None = ...) -> None: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy(self, **kwargs: Any) -> "Module": ...

class settings:
    @staticmethod
    def configure(*, lm: LM, track_usage: bool | None = ..., **kwargs: Any) -> None: ...

def context(*, lm: LM | None = ..., **kwargs: Any) -> ContextManager[None]: ...
