[openrouter]
R1 = { model = "deepseek/deepseek-r1:price" }
V3 = { model = "deepseek/deepseek-chat-v3-0324:price" }
GeminiFlash = { model = "google/gemini-2.0-flash-001" }
O3 = { model = "openai/o3-mini-high" }
GPT4oMini = { model = "openai/gpt-4o-mini" }

[bedrock]
Llama3dot370b = { model = "us.meta.llama3-3-70b-instruct-v1:0" }

[preferences]
fast_llm = "Llama3dot370b"
preferred_llm = "O3"