[project]
name = "path-summarize-alerts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools[parser]>=3.6.0",
    "baml-py==0.84.4",
    "boto3>=1.37.37",
    "botocore>=1.37.37",
    "jinja2>=3.1.5",
    "opentelemetry-api>=1.32.1",
    "opentelemetry-sdk>=1.32.1",
    "pydantic>=2.11.3",
    "tomli>=2.2.1",
]

[dependency-groups]
dev = [
    "deptry>=0.23.0",
    "path-summarize-alerts",
    "pip>=25.0.1",
]
