[project]
name = "path-summarize-alerts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools[parser]==3.11.0",
    "baml-py==0.86.1",
    "dyntastic>=0.18.0",
    "jinja2>=3.1.6",
    "pydantic>=2.11.7",
    "gepa>=0.0.12",
    # "dspy>=3.0.4",
    "backoff>=2.2",
    "joblib~=1.3",
    "openai>=0.28.1",
    "regex>=2023.10.3",
    "orjson>=3.9.0",
    "requests>=2.31.0",
    "pydantic>=2.0",
    "magicattr>=0.1.6",
    "litellm>=1.64.0",
    "diskcache>=5.6.0",
    "json-repair>=0.30.0",
    "tenacity>=8.2.3",
    "anyio",
    "asyncer==0.0.8",
    "cachetools>=5.5.0",
    "cloudpickle>=3.0.0",
    "rich>=13.7.1",
    "xxhash>=3.5.0",
    "numpy>=1.26.0",
]

[dependency-groups]
dev = [
    "boto3>=1.40.11",
    "botocore>=1.40.11",
    "deptry>=0.23.1",
    "pip>=25.2",
    "pyright>=1.1.404",
    "tqdm>=4.67.1",
    "wandb>=0.21.3",
    "boto3-stubs[essential]>=1.40.11",
    "tomli>=2.2.1",
    "types-jinja2>=2.11.9",
    "opentelemetry-api==1.32.1",
    "opentelemetry-sdk==1.32.1",
]

[tool.ruff]
# In addition to the standard set of exclusions, omit all tests, plus a specific file.
extend-exclude = [".aws-sam", "src/dspy"]

[tool.pyright]
include = ["src"]
strict = ["src/lib", "src/handlers", "src/*.py"]
ignore = ["src/baml_client", "src/dspy"]
venv = ".venv"
venvPath = "."
