import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.library'
    id 'kotlin-parcelize'
    id 'org.jetbrains.kotlin.android'
    id 'org.jmailen.kotlinter'
}

android {
    namespace 'ca.amandeep.path.prefs'
    compileSdk 35

    defaultConfig {
        minSdk 29

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(project.rootProject.file(".java-version").getText().trim()))
            vendor.set(JvmVendorSpec.ADOPTIUM)
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
        freeCompilerArgs += "-opt-in=kotlin.RequiresOptIn"
     }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    testOptions {
        unitTests.includeAndroidResources = true
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(project.rootProject.file(".java-version").getText().trim()))
        vendor.set(JvmVendorSpec.ADOPTIUM)
    }
}

java {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}

tasks.withType(KotlinCompile) {
    //noinspection GrDeprecatedAPIUsage
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation AndroidX.compose.ui
    implementation AndroidX.core.ktx
    implementation KotlinX.collections.immutable

    implementation 'com.github.ajalt:timberkt:_'
    implementation JakeWharton.timber

    implementation "androidx.datastore:datastore-preferences:1.1.4"

    testImplementation(Testing.junit4)
    testImplementation "com.google.truth:truth:_"
    testImplementation "com.google.truth.extensions:truth-java8-extension:_"
}
