name: Build with Gradle

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        cache: gradle
        java-version-file: ./android/.java-version
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Create google-services.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/PathTimes/PathTimes/android/app/google-services.json
    - name: Build
      run: ./gradlew build --scan --no-daemon
      working-directory: ./android

