name: Build with Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "serverless/path-summarize-alerts/.python-version"

    - name: Install the project
      run: uv sync --all-extras --dev --directory serverless/path-summarize-alerts/

    - name: "Compile python code with flake8"
      run: uv --directory serverless/path-summarize-alerts/ run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: "Check python formatting with black"
      run: uv --directory serverless/path-summarize-alerts/ run black . --check
